{% set name = "opentelemetry-instrumentation" %}
{% set version = "0.22b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-{{ version }}.tar.gz
  sha256: d27a808f162d7aa9111d3362991820b73c0c1848f9ad41c9c7f7626746a5c9d9

build:
  number: 0
  noarch: python
  entry_points:
    - opentelemetry-instrument = opentelemetry.instrumentation.auto_instrumentation:run
    - opentelemetry-bootstrap = opentelemetry.instrumentation.bootstrap:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - opentelemetry-api =={{ version }}
    - python >=3.5
    - wrapt >=1.0.0,<2.0.0

test:
  imports:
    - opentelemetry.instrumentation
  commands:
    - pip check
    - opentelemetry-instrument --help
    - opentelemetry-bootstrap --help
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/master/opentelemetry-instrumentation
  summary: Instrumentation Tools & Auto Instrumentation for OpenTelemetry Python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - twoodwark
    - mariusvniekerk
